before_script:
  - go get github.com/rooaaar/yaml-translation-utils/yamllinter
  - go get github.com/rooaaar/yaml-translation-utils/same-yaml
language: bash
notifications:
  email:
    on_failure: change
script:
  - bash scripts/linter.sh
  - bash scripts/identical/identical-fajuu-contactbutton.sh
  - bash scripts/identical/identical-fof-auth-discord.sh
