matrix:
  include:
    - after_success:
        - chmod +x scripts/push.sh
        - scripts/push.sh
      before_script:
        - go get github.com/git-chglog/git-chglog/cmd/git-chglog
      env:
        global:
          secure: kJrUgeEndwUw9M7aJwE+8t6ymqE+0xpIQWwWtJx1NUFiFxoVc7gIUPo4oaoDwFvHf8G4xYVDX7yauN3E6TDFX7NRjcFqXHB8Up3U66c7os+X5dd0zxQ7UOJgETkfuJEKNJjxSe01n6P698SL9JcRLabY073w6Ce6qCGBpJd7SxzlTCoA0UU6WryM3lwqqXHNTubMAlbaHOMvPR56bIY3+s9r9LG6DZWY6>
      language: go
      script:
        - git fetch origin --prune --tags
        - git-chglog --output CHANGELOG.md
    - before_script:
        - go get github.com/rooaaar/yaml-translation-utils/same-yaml
        - go get github.com/rooaaar/yaml-translation-utils/yamllinter
      env:
        global:
          secure: kJrUgeEndwUw9M7aJwE+8t6ymqE+0xpIQWwWtJx1NUFiFxoVc7gIUPo4oaoDwFvHf8G4xYVDX7yauN3E6TDFX7NRjcFqXHB8Up3U66c7os+X5dd0zxQ7UOJgETkfuJEKNJjxSe01n6P698SL9JcRLabY073w6Ce6qCGBpJd7SxzlTCoA0UU6WryM3lwqqXHNTubMAlbaHOMvPR56bIY3+s9r9LG6DZWY6>
      language: bash
      notifications:
        email:
          on_failure: change
      script:
        - bash scripts/identical/clarkwinkelmann-author-change.sh
        - bash scripts/identical/clarkwinkelmann-who-read.sh
        - bash scripts/identical/datitisev-dashboard.sh
        - bash scripts/identical/extiverse-bazaar.sh
        - bash scripts/identical/fajuu-contactbutton.sh
        - bash scripts/identical/flagrow-analytics.sh
        - bash scripts/identical/flagrow-impersonate.sh
        - bash scripts/identical/flagrow-users-list.sh
        - bash scripts/identical/fof-ads.sh
        - bash scripts/identical/fof-amazon-affiliation.sh
        - bash scripts/identical/fof-auth-discord.sh
        - bash scripts/identical/fof-auth-gitlab.sh
        - bash scripts/identical/fof-ban-ips.sh
        - bash scripts/identical/fof-byobu.sh
        - bash scripts/identical/fof-custom-footer.sh
        - bash scripts/identical/fof-default-group.sh
        - bash scripts/identical/fof-disposable-emails.sh
        - bash scripts/identical/fof-drafts.sh
        - bash scripts/identical/fof-follow-tags.sh
        - bash scripts/identical/fof-formatting.sh
        - bash scripts/identical/fof-frontpage.sh
        - bash scripts/identical/fof-gamification.sh
        - bash scripts/identical/fof-geoip.sh
        - bash scripts/identical/fof-ignore-users.sh
        - bash scripts/identical/fof-links.sh
        - bash scripts/identical/fof-mason.sh
        - bash scripts/identical/fof-masquerade.sh
        - bash scripts/identical/fof-merge-discussions.sh
        - bash scripts/identical/fof-moderator-notes.sh
        - bash scripts/identical/fof-nightmode.sh
        - bash scripts/identical/fof-pages.sh
        - bash scripts/identical/fof-passport.sh
        - bash scripts/identical/fof-polls.sh
        - bash scripts/identical/fof-pretty-mail.sh
        - bash scripts/identical/fof-prevent-necrobumping.sh
        - bash scripts/identical/fof-reactions.sh
        - bash scripts/identical/fof-recaptcha.sh
        - bash scripts/identical/fof-secure-https.sh
        - bash scripts/identical/fof-sentry.sh
        - bash scripts/identical/fof-share-social.sh
        - bash scripts/identical/fof-spamblock.sh
        - bash scripts/identical/fof-split.sh
        - bash scripts/identical/fof-stopforumspam.sh
        - bash scripts/identical/fof-subscribed.sh
        - bash scripts/identical/fof-terms.sh
        - bash scripts/identical/fof-upload.sh
        - bash scripts/identical/fof-user-directory.sh
        - bash scripts/identical/fof-username-request.sh
        - bash scripts/identical/fof-transliterator.sh
        - bash scripts/identical/kilowhat-mailing.sh
        - bash scripts/identical/kvothe-keyboard-shortcuts.sh
        - bash scripts/identical/kvothe-reply-to-see.sh
        - bash scripts/identical/kvothe-signup-button.sh
        - bash scripts/identical/michaelbelgium-discussion-views.sh
        - bash scripts/identical/michaelbelgium-profile-views.sh
        - bash scripts/identical/nomiscz-auth-steam.sh
        - bash scripts/identical/reflar-cookie-consent.sh
        - bash scripts/identical/reflar-doorman.sh
        - bash scripts/identical/reflar-latex.sh
        - bash scripts/identical/reflar-level-ranks.sh
        - bash scripts/identical/saleksin-auth-google.sh
        - bash scripts/identical/the-turk-diff.sh
        - bash scripts/identical/wiwatsrt-flarum-best-answer.sh
        - bash scripts/linter.sh
